name: Latest Blog Post Workflow
on:
  schedule: # Run workflow automatically
    # Runs every sunday at 04:05
    - cron: '5 4 * * sun'
  workflow_dispatch: # Run workflow manually
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "BLOGSPOT"
          feed_list: "https://feeds.feedburner.com/VisualBlender"
          commit_message: "Updated readme with the latest blog post"
